blockListPath: /app/resources/ipsum.txt
blockListDownloadURL: https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt
blockListHostName: localhost:8080
blockListRepoOwner: stamparm
blockListRepoName: ipsum

logging:
  level: INFO
  loggers:
    com.muun: DEBUG