blockListDownloadURL: https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt
blockListPath: /app/ipsum.txt
blockListRepoOwner: stamparm
blockListRepoName: ipsum

logging:
  level: INFO
  loggers:
    com.muun: DEBUG