blockListDownloadURL: https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt
blockListPath: ./ipsum.txt
blockListRepoOwner: arrodriguez
blockListRepoName: losiunicos

logging:
  level: INFO
  loggers:
    com.muun: DEBUG